import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header/Header'
import {CartProvider} from '../context/ContextCart'
import {FilterProvider} from '../context/FilterContext'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
        <FilterProvider>

      
      
        <Header />
        {children}

        </FilterProvider>
        </CartProvider>
      </body>
    </html>
  );
}
